version: 2
general:
  branches:
    only:
    - master
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run: docker build -t stylehopper/bikeshop.api:latest .
    - run: docker push stylehopper/bikeshop.api:latest