version: 2
general:
  branches:
    only:
    - develop
    - master
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run: docker build -t stylehopper/cra-goals:$CIRCLE_BRANCH .
    - run: docker push stylehopper/cra-goals:$CIRCLE_BRANCH